apiVersion: v1
kind: ConfigMap
metadata:
  name: setenv-webhook-configmap
data:
  setenvconfig.yaml: |
    env:
    - name: HTTP_PROXY
      value: http://USERNAME:PASSWORD@10.0.1.1:8080/
    - name: HTTPS_PROXY
      value: https://USERNAME:PASSWORD@10.0.0.1:8080/
    - name: NO_PROXY
      value: master.hostname.example.com
    - name: FOO
      value: "MANCHU"
